In [47]:
import numpy as np
import numpy.matlib
import pandas as pd
from tqdm.auto import tqdm
import math
import copy
from sklearn.metrics import mean_squared_error

In [2]:
data = pd.read_csv('data_train.csv')
sample = pd.read_csv('sampleSubmission.csv')

In [3]:
row_str = data["Id"].apply(lambda x: x.split("_")[0])
row_id = row_str.apply(lambda x: int(x.split("r")[1]) - 1)
col_str = data["Id"].apply(lambda x: x.split("_")[1])
col_id = col_str.apply(lambda x: int(x.split("c")[1]) - 1)

data['row'] = row_id
data['col'] = col_id

data_df = data.loc[:,['row', 'col', 'Prediction']]

In [4]:
data_df.head()

   row  col  Prediction
0   43    0           4
1   60    0           3
2   66    0           4
3   71    0           3
4   85    0           5

In [5]:
data_df = data_df.sort_values(by="row")
data_df.head()

         row  col  Prediction
700105     0  595           5
1139363    0  966           4
983770     0  778           3
371289     0  309           4
790973     0  642           5

In [56]:
# data_df.reset_index(drop = True).head()

   row  col  Prediction
0    0  595           5
1    0  966           4
2    0  778           3
3    0  309           4
4    0  642           5

In [109]:
# Try different k-values, works
k = 5
folds = np.append(np.matlib.repmat(np.arange(k)+1, 1, math.floor(shuffled_df.shape[0] / k)),
         (np.arange(k)+1)[0:shuffled_df.shape[0] % k])
assert folds.shape[0] == shuffled_df.shape[0]

In [6]:
def separate_in_folds(df, k = 5):
    
    # Create empty df to fill with shuffled data
    shuffled_df = pd.DataFrame(columns = ["row", "col", "Prediction"])
    
    # Shuffle data by row
    for i in tqdm(np.arange(10000)):
        num_rows = df[df['row'] == i].shape[0]
        row_sample = df[df['row'] == i].sample(n=num_rows)
        shuffled_df = shuffled_df.append(row_sample)
    
    # Assign folds to rows
    folds = np.append(np.matlib.repmat(np.arange(k)+1, 1, math.floor(shuffled_df.shape[0] / k)),
         (np.arange(k)+1)[0:shuffled_df.shape[0] % k])
    
    shuffled_df["Fold"] = folds
    
    # Return separate fold data frames in list, drop fold column
    fold_list = []
    for j in np.arange(k)+1:
        fold_list.append(shuffled_df[shuffled_df["Fold"] == j].drop('Fold', axis = 1))
    
    return fold_list

In [7]:
folds = separate_in_folds(df = data_df)

HBox(children=(FloatProgress(value=0.0, max=10000.0), HTML(value='')))

In [15]:
(np.arange(len(folds)) != 0) * 1

array([0, 1, 1, 1, 1])

In [16]:
# Write to csv's for consistency and quicker access

folds[0].to_csv('fold_1.csv')
folds[1].to_csv('fold_2.csv')
folds[2].to_csv('fold_3.csv')
folds[3].to_csv('fold_4.csv')
folds[4].to_csv('fold_5.csv')

In [18]:
fold_1 = pd.read_csv('fold_1.csv', index_col = 0)
fold_2 = pd.read_csv('fold_2.csv', index_col = 0)
fold_3 = pd.read_csv('fold_3.csv', index_col = 0)
fold_4 = pd.read_csv('fold_4.csv', index_col = 0)
fold_5 = pd.read_csv('fold_5.csv', index_col = 0)

fold_1.head()

         row  col  Prediction
15455      0    9           5
720365     0  604           5
1111258    0  920           3
1002582    0  791           3
1155420    0  981           2

In [32]:
folds = [fold_1, fold_2, fold_3, fold_4, fold_5]
folds[0]

          row  col  Prediction
15455       0    9           5
720365      0  604           5
1111258     0  920           3
1002582     0  791           3
1155420     0  981           2
...       ...  ...         ...
1168166  9999  990           2
1113768  9999  920           4
1123954  9999  935           3
685838   9999  585           4
555010   9999  474           4

[235391 rows x 3 columns]

In [95]:
RMSE = np.array([])
eigen_values = np.array([2,4,6,8,10,12,14,16,20,25,30,40,50,75,100])
for eig in eigen_values:
    
    
    # Cross-validation loop

    # Initialize scores array for RMSE's
    scores = np.array([])

    for i in np.arange(len(folds)): 
        # Make a copy of folds list to be able to use pop()
        fold_copy = copy.deepcopy(folds)

        test_set = fold_copy.pop(i)
        train_set = pd.concat([x for j,x in enumerate(fold_copy)])

        # Now train on training set
        # Insert any model for training here
        print("starting training...")
        pred_matrix = svd_mean_recommender(data = train_set, num_eigen = eig)

        # Predict on test_set
        print("starting predicting...")
        # Extract predictions
        row_ind = test_set.loc[:,'row']
        col_ind = test_set.loc[:,'col']
        preds = pred_matrix[row_ind, col_ind]

        # Add column to test_set with predictions from model
        test_set['Model Predictions'] = preds

        # Compute RMSE and add value to scores array
        print("compute RMSE")
        scores = np.append(scores, 
                           np.sqrt(mean_squared_error(test_set.loc[:,'Prediction'], test_set.loc[:,'Model Predictions'])))


    # Compute mean of scores for estimate of model performance
    RMSE = np.append(RMSE, np.mean(scores))

RMSE

starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE
starting training...
starting predicting...
compute RMSE

array([1.01578255, 1.01321002, 1.01168157, 1.01033203, 1.01021704,
       1.01014409, 1.01034768, 1.01046902, 1.01073634, 1.01164308,
       1.01245987, 1.01353457, 1.01499047, 1.01794976, 1.02072444])

In [41]:
def svd_mean_recommender(data, num_eigen):
    
    # 1. Compute data matrix with imputed means
    
    # Initialize empty
    data_matrix = np.zeros([10000,1000])
    data_matrix[:] = np.nan
    
    # Fill with observed values
    for i in np.arange(data.shape[0]):
        row_ind = data.iloc[i,0]
        col_ind = data.iloc[i,1]
        pred = data.iloc[i,2]
        data_matrix[row_ind, col_ind] = pred
    
    # Fill with column means
    item_means = np.apply_along_axis(np.nanmean, 0, data_matrix)
    for i in np.arange(data_matrix.shape[1]):
        data_matrix[np.isnan(data_matrix[:,i]), i] = item_means[i]
    
    # 2. Perform SVD (this is exercise 2.2 of series 2)
    
    u, s, vh = np.linalg.svd(data_matrix)
    
    s_diag = np.concatenate((np.diag(s), np.zeros((9000,1000))), axis = 0) # Represent singular values in matrix
    u_prime = np.matmul(u,np.sqrt(s_diag))
    v_prime = np.matmul(np.sqrt(s_diag), vh.T) # transpose since output vh is V^T
    
    # Compute prediction matrix. NOTE: currently not using square root matrices (prime) as recommended in exercise.
    # Tried this when first doing the exercise, got strange values and don't fully understand it. 
    predictions = np.matmul(u[:,0:num_eigen], np.matmul(s_diag[0:num_eigen,0:num_eigen], vh[0:num_eigen,:]))
    
    # Note that this is still complete matrix representation
    return predictions